<?xml version='1.0'?>
<package format='3'>
  <name>hpp_baxter</name>
  <version>9.0.0</version>
  <description>Wrappers for Baxter robot in HPP</description>
  <author>Joseph Mirabel</author>
  <maintainer email='guilhem.saurel@laas.fr'>Guilhem Saurel</maintainer>
  <license>BSD-2-Clause</license>

  <depend>coal</depend>
  <depend>example_robot_data</depend>

  <buildtool_depend>cmake</buildtool_depend>
  <build_depend>jrl_cmakemodules</build_depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>
